version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    container_name: db-wordpress
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: wp_data_base
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    container_name: phpmy-wordpress
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toor 
      UPLOAD_LIMIT: 20000K
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    ports:
      - '80:80'
    restart: always
    volumes: 
      - ./public/:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp_data_base
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_TABLE_PREFIX: wp_
    networks:
      - wpsite
networks:
  wpsite:
